server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommendController.java, server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommentController.java, server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseQueryController.java, server/src/main/java/com/codestates/hobby/domain/showcase/dto/ShowcaseDto.java, server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseCommentService.java, server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseService.java
- [#33] Showcase 및 Showcase Comment Service 1차 구현
- [#34] Showcase 및 Showcase Comment Controller 2차 구현
- Service에 메서드 선언만 해놓음
- 각각의 Controller 메서드마다 적절한 Service 메서드를 호출함
- DTO에 필드를 추가해서 컨트롤러에서 서비스로 넘기는 값들을 DTO에 할당함
- 페이징 파라미터를 받아야하는 `getAll` 메서드에 파라미터를 추가했습니다.
- 추후 페이징 파라미터들을 감싸는 클래스로 바꿀예정
- 핸들러 메서드에 필요한 파라미터들을 선언했습니다.
- `@AuthenticationPrincipal`
- 인증과정에서 **인증된** 회원의 정보는 `SecurityContextHolder`에 저장됩니다, 
- 이때 `Authentication` 객체의 `Principal` 필드에 저장되는 정보가 해당 어노테이션이 선언된 객체에 바인딩됩니다. (바인딩하는 클래스: `AuthenticationPrincipalArgumentResolver`)
- 주의할 점
1. 인증 유저가 없다면 **"String" 타입**의 "anonymousUser"가 값으로 할당됩니다.
2. `Principal` 필드에 어떤 타입의 객체를 할당했느냐에 따라서 클래스를 변경해야됩니다.
> ex. `Principal`에 `Member` 타입의 객체를 할당했다면 `@AuthenticationPrincipal Member authMember` 또는 `@AuthenticationPrincipal Object object` 형식으로 …
=> [BE/Showcase] Service 1차 및 Controller 2차 구현

server/build.gradle, server/src/main/java/com/codestates/hobby/global/config/MvcConfig.java, server/src/main/java/com/codestates/hobby/global/config/support/CustomPageRequest.java, server/src/main/java/com/codestates/hobby/global/config/support/PagingArgumentResolver.java, server/src/main/java/com/codestates/hobby/global/dto/MultiResponseDto.java, server/src/main/java/com/codestates/hobby/global/dto/PageInfo.java
- [#42]
- Jackson Object Mapper 설정 
- Build.gradle 라이브러리 정렬 및 추가
- Paging Argument Resolver 구현
- Multi Response Dto 구현
- Jackson Object Mapper 설정내용
- 직렬화할 때 값이 NULL인 키는 제외함
- FIELD를 통해서만 역직렬화 또는 직렬화함
- Build.gradle
- 추가된 라이브러리
- `lombok-mapstruct-binding`: lombok과 mapstruct를 같이 사용할 때 발생하는 충돌을 해결하는 라이브러리
- `commons-lang3`: 문자열이나 배열 등 자주 사용하는 기능을 구현한 유틸성 라이브러리
- 제거된 라이브러리
- `tomcat-embed-jasper`: 필요없는 라이브러리라서 회의때 제거하기로함
- Paging
- 컨트롤러마다 기본값이 다른데 어떻게 해결할 것인가?
- Sorting Type은 어떻게 중복을 제거할 수 있는가?
> 핸들러 메서드에 page, size 파라미터 지우고 `CustomPageRequest pageRequest`를 추가해서 사용할 수 있습니다.
=> [BE] 공통 설정

server/src/main/java/com/codestates/hobby/domain/category/controller/CategoryController.java, server/src/main/java/com/codestates/hobby/domain/category/dto/CategoryDto.java, server/src/main/java/com/codestates/hobby/domain/category/entity/Category.java, server/src/main/java/com/codestates/hobby/domain/category/mapper/CategoryMapper.java, server/src/main/java/com/codestates/hobby/domain/category/service/CategoryService.java, server/src/test/java/com/codestates/hobby/domain/category/controller/CategoryControllerTest.java, server/src/test/java/com/codestates/hobby/domain/category/service/CategoryServiceTest.java, server/src/test/java/com/codestates/hobby/domain/stub/CategoryStub.java
- [#33]
- [#34]
- [#35]
- [#36]
- Service 1차 구현
- Controller 클래스에 Service DI 및 메서드 호출
- Mapper 구현  및 Controller 클래스에 적용
- Service 및 Controller 테스트 케이스 작성
- DTO
- 취미의 그룹에 대해 응답하는 상황이 없어서 group 및 isGroup 필드 제거
- group이 ResponseDTO에 있을 경우 직렬화할 때 자기참조 때문에 SOE 예외 발생함
- Entity
- parent -> group으로 필드명 변경
- children -> categories로 필드명 변경
- ResponseDTO의 필드에 ResponseDTO가 있으면 자기참조가 발생합니다. `@JsonManagedReference/@JsonBackReference`를 사용해봤지만 자기참조시에는 사용하기 힘들어서 우선 group 필드를 제거했습니다.
- Category의 경우 parent 또는 chlidren보다 group, categories(또는 hobbies)가 적절할 거 같아 임시로 바꿔봤는데 더 적절한 다른 이름이 있는지 아니면 이전 이름이 괜찮은지 궁금합니다.
=> [Category] Service 1차, Controller 2차, Mapper 구현

client/src/App.js, client/src/components/molecules/PostHeader.js, client/src/components/molecules/PostUserInfo.js, client/src/components/molecules/comments/Comment.js, client/src/components/molecules/comments/CommentContentsContainer.js, client/src/components/molecules/comments/CommentHeader.js, client/src/components/molecules/comments/CommentInputContainer.js, client/src/components/organisms/posts/PostCommentContainer.js, client/src/components/organisms/posts/PostContent.js, client/src/components/organisms/posts/PostHeaderContainer.js, client/src/components/organisms/posts/PostSubHeaderContainer.js, client/src/components/templates/PostPage.js
- Post Header, Index, Body, Comment 컴포넌트 분리
- Comment 컴포넌트 molecules로 추가
closed #40
=> [FE] Post Page 레이아웃 구현

server/build.gradle, server/src/main/java/com/codestates/hobby/domain/fileInfo/dto/ImageType.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/service/FileInfoService.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/service/GCSFileInfoService.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/service/S3FileInfoService.java, server/src/main/java/com/codestates/hobby/global/config/GCSConfig.java
- [#33 ]
- `FileInfoService`의 `genereteURL` 메서드를 실행하기 위해서는 다음과 같은 파라미터가 필요합니다.
- `contentType` (ex. `image/png`, image/webp`...)
- `basePath`: 클라우드 스토리지의 버킷에 저장될 경로
- 메서드의 결과는 Map 형태로 두 가지의 String을 가지고 있습니다.
- `url`: 클라우드 저장소에 이미지를 저장하기 위한 url
- `savedFilename`: 버켓에 저장될 이미지의 위치
- 위의 정보로 클라이언트가 업로드하는 방법
- `curl -X PUT -H 'Content-Type: {image/png}' --upload-file {my-file} {url}`
- 메서드의 반환타입이 Map이라 호출하는 쪽에서 키값을 알아야해서 불편할수도 있는데 FileInfoDTO를 만들까요??
**해당 기능을 이용하기 위해서는 반드시 GCP의 사용자 키 파일이 필요합니다**
=> [BE] FileInfo service 구현

client/src/App.js, client/src/components/organisms/search/SearchResultTitle.js, client/src/components/templates/Search.js
- #51 
- Search 페이지 구성 컴포넌트 추가
- Search 템플릿 추가
close #51
=> [FE/Search] 페이지 레이아웃 구현

server/src/main/java/com/codestates/hobby/domain/fileInfo/controller/FileInfoController.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/dto/BasePath.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/dto/FileInfoDto.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/dto/ImageType.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/dto/SignedURL.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/service/FileInfoService.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/service/GCSFileInfoService.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/service/S3FileInfoService.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/support/BasePathConverter.java, server/src/main/java/com/codestates/hobby/global/config/MvcConfig.java
- [#34 ]
- 컨트롤러 구현
- POST `/{base-path}/files` 요청시 signedURL 발급
- 요청 DTO
- `Type`: 저장할 수 있는 이미지의 타입 (png, jpeg, webp, gif) 
- 응답 DTO
- `SignedURL`: 이미지를 업로드할 수 있는 임시 URL
- `FileURL`: 이미지를 조회할 수 있는 이미지의 링크
- `Type`: 업로드할 때 `Content-Type`으로 지정해야되는 타입
- DTO에 `ContentType`을 반환하도록 `ImageType` 필드 추가
- `BasePath` 및 `ImageType`을 `Enum` 타입으로 변경
=> [BE/FileInfo] Controller 구현 및 리펙토링

client/src/App.js, client/src/components/atoms/Buttons.js, client/src/components/organisms/PageHeader.js, client/src/components/organisms/listcontents/ListHeader.js, client/src/components/templates/PostList.js, client/src/components/templates/SeriesList.js
- 외부 디자인 구현
- 내부 타이틀 및 컴포넌트 추가 기능 구현
* headerTitle: Header 왼쪽 타이틀
* headerSubTitle: Header 왼쪽 상단 타이틀
* asideHeader: Header 오른쪽 추가 컴포넌트
* height: Header 외부 컨테이너의 높이
```javascript
<PageHeader
headerTitle="POSTS IN CATEGORY"
headerSubTitle="Subtitle"
asideHeader={<BlueShadowButton>Create</BlueShadowButton>}
height="200px"
/>
```
closes #63
=> [FE] Page Header 컴포넌트 구현

server/build.gradle, server/src/main/java/com/codestates/hobby/domain/category/controller/CategoryController.java, server/src/main/java/com/codestates/hobby/domain/category/entity/Category.java, server/src/main/java/com/codestates/hobby/domain/category/mapper/CategoryMapper.java, server/src/main/java/com/codestates/hobby/domain/category/repository/CategoryRepository.java, server/src/main/java/com/codestates/hobby/domain/category/service/CategoryService.java, server/src/main/java/com/codestates/hobby/global/config/CachingConfig.java, server/src/main/resources/application.yml, server/src/main/resources/data.sql, server/src/test/java/com/codestates/hobby/domain/category/controller/CategoryControllerTest.java, server/src/test/java/com/codestates/hobby/domain/category/controller/CategoryIntegrationTest.java, server/src/test/java/com/codestates/hobby/domain/category/repository/CategoryRepositoryTest.java, server/src/test/java/com/codestates/hobby/domain/category/service/CategoryServiceTest.java, server/src/test/java/com/codestates/hobby/domain/stub/CategoryStub.java, server/src/test/java/com/codestates/hobby/utils/ControllerTest.java
- 하이버네이트 L2 Cache 적용 (엔티티 및 쿼리)
- Category Entity 양방향 매핑으로 변경
- 통합테스트 및 Repository Layer 테스트 실행
- 카테고리 스텁데이터 구현
- `ServiceTest`: 단위테스트로 변경
- `ControllerTest`: `BeforeAll` 접근제어자 protect로 변경
- 이건 하이버네이트 2차 캐시 적용한겁니다
- `category` 브랜치는 스프링 캐시 적용한건데 둘 중 어떤게 더 나을까요? 
- 하이버네이트 
- (장) 엔티티 조인시 카테고리가 캐싱됐다면 그 카테고리를 불러올 수 있다.
- (단) 2차 캐시가 활성화돼서 다른 엔티티도 먼저 2차 캐시에 접근한다.
- 스프링 캐시
- (장) 구현이 간편하다.
- (단) 엔티티 조인시 캐싱된 카테고리를 가져올 수 없다.
=> [BE/Cat] 하이버네이트 L2 Cache 적용 및 테스트

server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommendController.java, server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommentController.java, server/src/main/java/com/codestates/hobby/domain/post/controller/PostQueryController.java, server/src/main/java/com/codestates/hobby/domain/post/dto/PostDto.java, server/src/main/java/com/codestates/hobby/domain/post/mapper/PostMapper.java
- Post매핑 시 SeriesPosts의 url 제공
- Controller return값 일치를 위한 수정
- Series가 존재하지 않는 Post를 위한 리팩토링
- PostDto의 Series와 SeriesPosts값 수동 매핑
=> [BE/Post] Controller, Dto, Mapper 리펙토링 

server/src/main/java/com/codestates/hobby/domain/category/service/CategoryService.java, server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java, server/src/main/java/com/codestates/hobby/domain/post/controller/PostQueryController.java, server/src/main/java/com/codestates/hobby/domain/post/mapper/PostMapper.java, server/src/main/java/com/codestates/hobby/domain/post/service/PostCommentService.java, server/src/main/java/com/codestates/hobby/domain/post/service/PostService.java, server/src/main/java/com/codestates/hobby/domain/series/service/SeriesService.java, server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseCommentService.java, server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseService.java, server/src/main/java/com/codestates/hobby/global/advice/GlobalExceptionAdvice.java, server/src/main/java/com/codestates/hobby/global/exception/BusinessLogicException.java, server/src/main/java/com/codestates/hobby/global/exception/ExceptionCode.java, server/src/main/java/com/codestates/hobby/global/response/ErrorResponse.java, server/src/test/java/com/codestates/hobby/domain/post/service/PostServiceTest.java
- 예외 처리를 클라이언트에게 전송하기 위해 GlobalExceptionAdvice 생성
- Custom Exception 생성
- 에러 코드와 response 생성
- Vaildation  에러 핸들링
- Serive 계층 예외 처리 수중
- showcase와 category의 serivce 계층 에러를 수정하며, 속성값을 같이 보내주던 기존의 구현이 사라졌습니다. 혹시 필요하시다면 말씀 해주세요!
- setSeriesPostUrl 메서드를 Mapper로 이동하였습니다.
=> [BE] Service 계층 3차 구현

server/src/main/java/com/codestates/hobby/domain/fileInfo/entity/FileInfo.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/entity/FileURL.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/mapper/FileInfoMapper.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/repository/FileInfoRepository.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/service/GCSFileInfoService.java, server/src/test/java/com/codestates/hobby/domain/fileInfo/service/FileInfoServiceTest.java, server/src/test/java/com/codestates/hobby/domain/stub/FileInfoStub.java
- `getPath()` 메서드 제거 
- `Token`으로만 경로를 얻을 수 있게 변경
- `Repository` 메서드 변경
- Embedded 타입인 `FileURL`에 맞춰서 수정함
- `GCSFileInfoService` 로직 변경 
- 요청 타입[신규, 조회]에 대한 분기를 Service에서 처리하도록 수정함
=> [BE/FileInfo] FileInfo 오류 수정

server/src/test/java/com/codestates/hobby/domain/category/controller/CategoryControllerTest.java, server/src/test/java/com/codestates/hobby/utils/ControllerTest.java, server/src/test/java/com/codestates/hobby/utils/IntegrationTest.java, server/src/test/java/com/codestates/hobby/utils/TestUtils.java
- 통합테스트 전용 추상클래스 구현
- 테스트용 유틸 클래스 구현
- 통합테스트할 때 `IntegrationTest`를 상속받으시면 됩니다.
=> [BE/Test] 테스트 유틸 클래스 분리

server/.gitignore, server/build.gradle, server/src/main/java/com/codestates/hobby/ServerApplication.java, server/src/main/java/com/codestates/hobby/domain/auth/entity/Certification.java, server/src/main/java/com/codestates/hobby/domain/auth/event/CertificationCreatedEvent.java, server/src/main/java/com/codestates/hobby/domain/auth/service/CertificationEventHandler.java, server/src/main/java/com/codestates/hobby/global/config/GCSConfig.java, server/src/main/java/com/codestates/hobby/global/support/mail/EmailService.java, server/src/main/java/com/codestates/hobby/global/support/mail/GoogleEmailService.java, server/src/main/java/com/codestates/hobby/global/support/mail/MockEmailService.java, server/src/main/resources/application.yml, server/src/main/resources/templates/email-certification-template.html
- 구글 기반 이메일 전송 기능 구현
- Certification 생성 이벤트와 핸들러 구현
- profile('mock')을 지정하지 않을시 구글 서비스가 지정됩니다.
- mock 프로파일을 지정하고 실행해야됩니다.
- 구글 이메일 기능을 실행하기 위해서는 앱 비밀번호가 설정된 구글 이메일이 필요합니다. [link](https://support.bespinglobal.com/ko/support/solutions/articles/73000545275--gmail-%EC%95%B1-%EB%B9%84%EB%B0%80%EB%B2%88%ED%98%B8-%EC%83%9D%EC%84%B1%EB%B0%A9%EB%B2%95)
=> [BE/Mail] 이메일 전송 기능 구현

server/src/main/java/com/codestates/hobby/domain/auth/controller/HomeController.java, server/src/main/java/com/codestates/hobby/domain/common/Writing.java, server/src/main/java/com/codestates/hobby/domain/post/dto/PostCommentDto.java, server/src/main/java/com/codestates/hobby/domain/post/entity/Post.java, server/src/main/java/com/codestates/hobby/domain/post/mapper/PostCommentMapper.java, server/src/main/java/com/codestates/hobby/domain/series/entity/Series.java, server/src/test/java/com/codestates/hobby/domain/post/controller/PostCommentControllerTest.java, server/src/test/java/com/codestates/hobby/domain/post/controller/PostControllerTest.java, server/src/test/java/com/codestates/hobby/domain/post/service/PostServiceTest.java, server/src/test/java/com/codestates/hobby/domain/post/tempTest/AsyncTest.java
- Post와 Series 테이블을 Super-Type Writing의 Sub-Type으로 변경
- 각 엔티티도 상속을 통해 구현
##기타
- 이제 Post 및 Series는 Writing 클래스의 DTYPE 속성을 통해 구별되며, 비즈니스 로직의 변경 사항은 없습니다.
=> [Be/Post, Series] post, series 엔티티 및 DB 구성 방식 변경 

server/build.gradle, server/src/main/java/com/codestates/hobby/ServerApplication.java, server/src/main/java/com/codestates/hobby/domain/common/BaseEntity.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/entity/FileInfo.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/mapper/FileInfoMapper.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/service/GCSFileInfoService.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/service/MockFileInfoService.java, server/src/main/java/com/codestates/hobby/domain/fileInfo/service/S3FileInfoService.java, server/src/main/java/com/codestates/hobby/domain/notifcation/entity/Notification.java, server/src/main/java/com/codestates/hobby/domain/showcase/entity/Showcase.java, server/src/main/java/com/codestates/hobby/domain/subscription/entity/Subscription.java, server/src/main/java/com/codestates/hobby/global/config/GCSConfig.java, server/src/main/java/com/codestates/hobby/global/dto/ErrorResponse.java, server/src/main/java/com/codestates/hobby/global/exception/GlobalExceptionAdvice.java, server/src/main/java/com/codestates/hobby/global/support/mail/GoogleEmailService.java, server/src/main/java/com/codestates/hobby/global/support/mail/MockEmailService.java, server/src/main/resources/application-local.yml, server/src/main/resources/application-prod.yml, server/src/main/resources/application.yml, server/src/main/resources/data.sql
- `Connection Pool` 설정
- `max, min connection`: 기본값인 10으로 유지
- `connection timeout`: 3초
- `max-timeout`: 기본값 30분으로 유지 (변경시 db의 `timeout`을 +2~5초로 변경해야함)
- `profile`: `prod`, `local`로 나눔
- `dependency`: mysql 추가함
- `entity`
- 시간 관련 필드의 컬럼 타입을 `timestamp`로 변경함
- `int` 필드의 컬럼 타입 `tinyint`로 변경함 
- `fileInfo` 엔티티의 필드명을 `fileIndex`로 변경함
- `global` 패키지 정리
- `advice`: `exception`으로 이동
- `error response`: `dto`로 이동
- `propertySource` 제거함
- `prod` 프로파일에서 실행시 필요한 환경변수
- `STORAGE_BUCKET`: 클라우드 저장소의 버킷 이름
- `DB_HOST`: 원격 db 주소 (포트번호는 3306 고정)
- `EMAIL_USERNAME`: 이메일 api 사용할 수 있는 구글 계정
- `EMAIL_PASSWORD`: 구글 계정의 앱 비밀번호
=> [BE/Deploy] 배포를 위한 Profile 재설정

client/src/components/pages/LogInPage.js, client/src/components/pages/SignupPage.js
- OAuth 후순위 개발 진행으로 인한 OAuth 컨테이너 제거
=> [FE] OAuth 컨테이너 제거

server/src/main/java/com/codestates/hobby/ServerApplication.java, server/src/main/java/com/codestates/hobby/domain/auth/controller/LoginController.java, server/src/main/java/com/codestates/hobby/domain/auth/dto/CertificationCreatedEvent.java, server/src/main/java/com/codestates/hobby/domain/auth/dto/CertificationPatchRequest.java, server/src/main/java/com/codestates/hobby/domain/auth/entity/Certification.java, server/src/main/java/com/codestates/hobby/domain/auth/repository/CertificationRepository.java, server/src/main/java/com/codestates/hobby/domain/auth/service/CertificationEventHandler.java, server/src/main/java/com/codestates/hobby/domain/auth/service/CertificationService.java, server/src/main/java/com/codestates/hobby/domain/member/repository/MemberRepository.java, server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java, server/src/main/java/com/codestates/hobby/global/dto/ErrorResponse.java, server/src/main/java/com/codestates/hobby/global/exception/ExceptionCode.java, server/src/main/java/com/codestates/hobby/global/exception/GlobalExceptionAdvice.java, server/src/main/java/com/codestates/hobby/global/support/mail/GoogleEmailService.java, server/src/main/resources/application-prod.yml
- 이메일 인증 기능 구현
- 이메일 인증 엔티티, DTO 구현
- 인증 서비스 구현
- 회원가입시 사용된 이메일의 인증여부 확인하는 로직 추가
- 비동기 처리를 EmailService에서 EventHandler가 하도록 수정
- `ControllerAdvice`의 리턴 값에 메세지 포함하도록 수정
- `LoginController` 에 `RequestMapping("/auth")` 어노테이션 추가함
=> [BE/Cert] 이메일 인증 기능 구현

server/src/main/java/com/codestates/hobby/domain/showcase/dto/ShowcaseCommentDto.java, server/src/main/java/com/codestates/hobby/global/config/SecurityConfig.java, server/src/main/java/com/codestates/hobby/global/exception/GlobalExceptionAdvice.java, server/src/test/java/com/codestates/hobby/domain/category/controller/CategoryIntegrationTest.java
- `Advice`
- 반환시 예외 메세지 보내도록 변경
- `HttpMediaTypeNotSupportedException` 추가
- `Security`: authorize http requests 변경
- `Showcase Comment Dto`: 추상화
=> [BE/Config] 예외 및 Security 설정 리펙토링

server/src/main/java/com/codestates/hobby/domain/member/dto/MemberDto.java, server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java, server/src/main/java/com/codestates/hobby/domain/member/mapper/MemberMapper.java, server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
- Member Entity에 defaultProfile 컬럼 추가
- 가입 시 기본 프로필 사진을 지정해줌
- 사진을 변경하면 추가한 사진의 URL이 fileInfo에 저장되며 defaultProfile이 해당 URL로 변경됨
- response시 fileinfo의 fileUrl이 아닌 defaultProfile를 응답하도록 변경
=> [Be/member] 가입 로직 변경
