codestates-seb/seb41_main_009

.gitignore
server/src/main/java/com/codestates/hobby/domain/category/controller/CategoryController.java
server/src/main/java/com/codestates/hobby/domain/notifcation/controller/NotificationController.java

- 카테고리 컨트롤러 1차 구현
- 카테고리 그룹 목록을 조회하는 핸들러 구현
- 특정 그룹의 카테고리 목록을 조회하는 핸들러 구현
- 모든 카테고리 목록을 조회하는 핸들러 구현
- Notification에서 브랜치를 생성해서 Notification Controller에 대한 내용도 포함되었습니다.

[BE/Category] Controller  1차 구현

---

.gitignore
server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommendController.java
server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommentController.java
server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseQueryController.java

- Showcase, Showcase Comment에 대한 컨트롤러 1차 구현
- 쇼케이스
- 생성, 수정, 삭제 핸들러 구현
- 목록 조회, 개별 조회, 특정 유저에 대한 목록 조회, 특정 카테고리에 대한 목록 조회 핸들러 구현
- 쇼케이스 댓글
- 댓글 생성, 수정, 삭제, 목록 조회 핸들러 구현

[BE/Showcase] Controller 1차 구현

---

server/src/main/java/com/codestates/hobby/domain/series/controller/SeriesController.java

- 시리즈 컨트롤러 1차 구현
- 시리즈를 생성/수정/삭제 핸들러 구현
- 특정 카테고리에 대한 시리즈 목록 조회 핸들러 구현
- 시리즈에 포함된 포스트 목록 조회 핸들러 구현
- 특정 멤버에 대한 시리즈 리스트 조회 핸들러 구현

[BE/Series] Controller 1차 구현

---

server/src/main/java/com/codestates/hobby/domain/member/controller/MemberController.java
server/src/main/java/com/codestates/hobby/domain/series/controller/SeriesController.java

- 멤버 컨트롤러 1차 구현
- 가입, 정보 수정, 탈퇴 핸들러 구현
- 특정 멤버의 정보 조회 핸들러 구현
- 로그인, 로그아웃은 후에 추가하겠습니다.

[BE/Member] Controller 1차 구현

---

server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
server/src/main/java/com/codestates/hobby/domain/subscription/controller/SubscriptionController.java
server/src/main/java/com/codestates/hobby/domain/subscription/entity/Subscription.java

- Subscription Controller의 1차 구현
- 다른 회원을 구독하는 핸들러
- 구독을 취소하는 핸들러
- 구독중인 목록 조회
- 회원을 구독하는 회원 목록 조회
- 구독중인 회원들의 쇼케이스 목록 조회
- 구독중인 회원들의 포스트 목록 조회
- 다음과 같은 핸들러를 구독 컨트롤러에 구현하는게 맞을까요??
- 구독중인 회원들의 쇼케이스 목록 조회
- 구독중인 회원들의 포스트 목록 조회

[BE/Sub] Controller 1차 구현

---

server/src/main/java/com/codestates/hobby/domain/category/dto/CategoryDto.java

- [#6] Category Dto 구현
- Category Dto 구현
- Request Body가 필요없어서 Response만 구현했습니다.

[BE/Category] DTO 구현

---

server/src/main/java/com/codestates/hobby/domain/notifcation/controller/NotificationController.java
server/src/main/java/com/codestates/hobby/domain/notifcation/dto/NotificationDto.java

- [#6 ] Notification DTO 구현 및 Controller 리펙토링
- Notification Dto 구현
- 알람 확인시 제거되는 것을 알리기 위해 GetMapping을 DeleteMapping으로 변경
- Request Body가 필요없어서 Response만 구현했습니다.

[BE/Noti] DTO 및 Controller 리펙토링

---

server/src/main/java/com/codestates/hobby/domain/subscription/dto/SubscriptionDto.java

- [#6] Subscription Dto 구현
- Subscription Dto 구현
- Request Body가 필요없어서 Response만 구현했습니다.

[BE/Sub] DTO 구현

---

server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommendController.java
server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommentController.java
server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseQueryController.java
server/src/main/java/com/codestates/hobby/domain/showcase/dto/ShowcaseCommentDto.java
server/src/main/java/com/codestates/hobby/domain/showcase/dto/ShowcaseDto.java

- [#6] Showcase DTO 구현 및 Controller 리펙토링
- Showcase DTO 구현 
- Showcase Comment DTO 구현
- 구현된 DTO를 핸들러 메서드의 파라미터에 추가함

[BE/Showcase] DTO 구현 및 Controller 리펙토링

---

server/src/main/java/com/codestates/hobby/domain/member/controller/MemberController.java
server/src/main/java/com/codestates/hobby/domain/member/dto/MemberDto.java
server/src/main/java/com/codestates/hobby/domain/series/controller/SeriesController.java
server/src/main/java/com/codestates/hobby/domain/series/dto/SeriesDto.java

- Member [#6]
- Member DTO 1차 구현 
- 구현된 DTO를 Cotroller에 적용

[BE/Member] DTO 1차 구현 및 Controller 리팩토링

---

server/src/main/java/com/codestates/hobby/domain/member/controller/MemberController.java
server/src/main/java/com/codestates/hobby/domain/member/dto/MemberDto.java
server/src/main/java/com/codestates/hobby/domain/series/controller/SeriesController.java
server/src/main/java/com/codestates/hobby/domain/series/dto/SeriesDto.java

- Series [#6]
- Series DTO 1차 구현 
- 구현된 DTO를 Cotroller에 적용
- 시리즈는 썸네일만 필요해서 FileInfo와 OneToOne 매핑으로 변경하고 싶은데 괜찮을까요?

[BE/Series] DTO 1차 구현 및 Controller 리펙토링

---

client/src/App.js
client/src/components/molecules/SidebarMenu.js
client/src/components/organisms/Sidebar.js

- Sidebar 컴포넌트 구성
- Sidebar menu 컴포넌트 구성
closes #25

[FE] Sidebar 컴포넌트 구현

---

client/.eslintrc.js
client/src/App.js
client/src/components/organisms/Showcase/ShowcaseModal.js
client/src/components/organisms/Showcase/Showcasebox.js
client/src/components/templates/Showcase.js

- Showcase template 작성
- Showcasebox, ShowcaseModal organism 작성
closed #26

[FE/Showcase] 레이아웃 구현

---

client/src/App.js
client/src/GlobalStyle.js
client/src/components/atoms/Buttons.js

<strong>기본적으로 a태그로 구현한 점 참고 부탁드립니다!</strong>
- 기본 버튼 구현
- Shadow 포함 버튼 구현
closed #55

[FE] Button 컴포넌트 구현

---

server/src/main/java/com/codestates/hobby/domain/member/controller/MemberController.java
server/src/main/java/com/codestates/hobby/domain/member/dto/MemberDto.java
server/src/main/java/com/codestates/hobby/domain/member/mapper/MemberMapper.java
server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java

- Member [#33]
- Member [#34]
- Member [#35]
- Service의 대략적인 구현
- Controller에 Service 클래스를 DI하고 해당하는 메서드를 호출
- Mapstruct를 이용해 Mapper 적용
- Dto에 profileImage 추가

[BE/Member] Service 1차, Controller 2차, Mapper 구현 및 Dto 리팩토링

---

server/src/main/java/com/codestates/hobby/domain/series/controller/SeriesController.java
server/src/main/java/com/codestates/hobby/domain/series/dto/SeriesDto.java
server/src/main/java/com/codestates/hobby/domain/series/entity/Series.java
server/src/main/java/com/codestates/hobby/domain/series/mapper/SeriesMapper.java
server/src/main/java/com/codestates/hobby/domain/series/service/SeriesService.java

- Series [#33]
- Series [#34]
- Series [#35]
- Service의 대략적인 구현
- Controller에 Service 클래스를 DI하고 해당하는 메서드를 호출
- Mapstruct를 이용해 Mapper 적용
- FileInfo와 OneToOne 매핑으로 변경
- Dto에 thumbnail 추가

[BE/Series] Service 1차, Controller 2차, Mapper 구현 및 Dto 리팩토링

---

server/src/main/java/com/codestates/hobby/domain/notifcation/controller/NotificationController.java
server/src/main/java/com/codestates/hobby/domain/notifcation/service/NotificationService.java

- [#33 ]
- 옵셔널이라 Controller 부터는 구현하지 않았습니다.

[BE] Notification Service 1차 구현

---

server/src/main/java/com/codestates/hobby/domain/subscription/controller/SubscriptionController.java
server/src/main/java/com/codestates/hobby/domain/subscription/service/SubscriptionService.java

- [#33 ]
- 옵셔널이라 Controller 2차 구현부터 하지 않았습니다.

[BE] Subscription Service 1차 구현

---

client/src/App.js
client/src/GlobalStyle.js
client/src/components/organisms/Navigator.js
client/src/components/organisms/Sidebar.js
client/src/components/organisms/user/UserContentBox.js
client/src/components/organisms/user/UserTitle.js
client/src/components/templates/Showcase.js
client/src/components/templates/User.js
client/src/components/templates/UserEdit.js
client/src/routes/PublicRoute.js

- [#47 ]
- [#66 ]
- 레이아웃 사이즈와 관련된 CSS Variable 추가
- 사이드바 CSS 변경
- 전체 레이아웃 포지션 조정
- User 템플릿, UserEdit 템플릿 작성
- User 페이지
- UserEdit 페이지
closed #47 
closed #66

[FE] User, UserEdit 페이지 레이아웃 구현

---

server/src/test/java/com/codestates/hobby/domain/member/MemberControllerTest.java
server/src/test/java/com/codestates/hobby/domain/member/MemberServiceTest.java

- Member [#36]
- Service와 Controller에 대한 테스트 케이스를 작성

[BE/Member] 테스트 케이스 작성

---

server/src/test/java/com/codestates/hobby/domain/series/SeriesControllerTest.java
server/src/test/java/com/codestates/hobby/domain/series/SeriesServiceTest.java

- Series [#36]
- Service와 Controller에 대한 테스트 케이스를 작성

[BE/Series] 테스트 케이스 작성

---

client/src/App.js
client/src/components/atoms/AcrylicBase.js
client/src/components/atoms/FontStyle.js

[FE] Font Style Component 구현 

---

client/src/App.js
client/src/components/molecules/SearchInput.js
client/src/components/organisms/Navigator.js

- 로고 삽입 및 Root Link 연결
- Search Input 컴포넌트 생성 및 검색 시 Link 연결
- Login, Signup 버튼 구현
- Session에 따라 Login, Signup / Mypage, Logout 변경되도록 구현 예정
closes #90

[FE] Header 컴포넌트 구현

---

server/src/main/java/com/codestates/hobby/domain/showcase/entity/Showcase.java
server/src/main/java/com/codestates/hobby/domain/showcase/entity/ShowcaseImage.java
server/src/main/java/com/codestates/hobby/domain/showcase/repository/ShowcaseImageRepository.java
server/src/main/java/com/codestates/hobby/domain/showcase/repository/ShowcaseRepository.java
server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseService.java
server/src/test/java/com/codestates/hobby/domain/showcase/service/ShowcaseServiceTest.java
server/src/test/java/com/codestates/hobby/utils/DatabaseCleanup.java

- Showcase <-> FileInfo 조인 테이블 매핑 방법 변경
- DB 데이터를 지우는 유틸 클래스 구현
- Showcase 생성, 수정 테스트 구현
- Showcase <-> FileInfo 조인 테이블을 어노테이션에서 클래스로 변경함

[BE/Showcase] JoinTable 매핑 방법 변경

---

client/src/App.js
client/src/components/molecules/InputCard.js
client/src/components/molecules/SignUpMessage.js
client/src/components/molecules/stickerLabel/SplashStickerLabel.js
client/src/components/molecules/stickerLabel/StickerLabel.js
client/src/components/molecules/stickerLabel/TiltedContainer.js
client/src/components/organisms/Loginbox.js
client/src/components/organisms/Navigator.js
client/src/components/organisms/Openidbox.js
client/src/components/templates/LogIn.js
client/src/components/templates/Signin.js
client/src/constants/Messages.js
client/src/constants/Regexp.js
client/src/functions/isValid.js

- Splash 이미지 연결
- Email, PW 확인 로직 구현
- Sign Up page 링크 구현
- OAuth 버튼 레이아웃 설정 및 컴포넌트 연결
closes #114

[FE] Login Page 구현

---

server/src/main/java/com/codestates/hobby/domain/member/controller/MemberController.java
server/src/main/java/com/codestates/hobby/domain/member/dto/MemberDto.java
server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
server/src/main/java/com/codestates/hobby/domain/member/mapper/MemberMapper.java
server/src/main/java/com/codestates/hobby/domain/member/repository/MemberRepository.java
server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java

- Member [#72]
- Member  [#73]
- Repository 구현
- 비지니스 로직 추가
- 엔티티도 바뀌었습니다..확인 부탁드립니다.

[Be/Member] Data access 계층 구현, Service 2차 구현

---

client/src/components/organisms/Loginbox.js
client/src/components/organisms/Signupbox.js
client/src/components/templates/Signup.js
client/src/constants/Messages.js

- 비밀번호 체크 로직 구현
- 이메일 인증 로직 백엔드와 협의 후 페이지 수정 혹은 추가 예정
closes #115

[FE] 회원가입 페이지 구현

---

client/src/App.js
client/src/components/templates/404ErrorPage.js

- 404 페이지 생성 및 Route 연결
- 전체 디자인 구현
- 홈, 뒤로가기 버튼 구현
closes #116

[FE] 404 에러 페이지 구현

---

server/src/main/java/com/codestates/hobby/domain/series/controller/SeriesController.java
server/src/main/java/com/codestates/hobby/domain/series/dto/SeriesDto.java
server/src/main/java/com/codestates/hobby/domain/series/entity/Series.java
server/src/main/java/com/codestates/hobby/domain/series/mapper/SeriesMapper.java
server/src/main/java/com/codestates/hobby/domain/series/repository/SeriesRepository.java
server/src/main/java/com/codestates/hobby/domain/series/service/SeriesService.java

- Series [#72]
- Series  [#73]
- Repository 구현
- 비지니스 로직 추가
- pageRequest로 페이지네이션 정보 한번에 받기

[Be/Series] Data access 계층 구현, Service 2차 구현 

---

server/src/main/java/com/codestates/hobby/domain/member/controller/MemberController.java
server/src/main/java/com/codestates/hobby/domain/member/dto/MemberDto.java
server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
server/src/main/java/com/codestates/hobby/domain/member/mapper/MemberMapper.java
server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
server/src/main/java/com/codestates/hobby/global/config/SecurityConfig.java

- Member [#74]
- email, password, nickname의 유효성 검증을 추가 하였습니다.
-  fileInfo와의 조인 테이블을 없애고 그에 따라 controller와 service를 수정하였습니다.

[Be/Member] 유효성 검증 구현 및 리펙토링

---

server/src/main/java/com/codestates/hobby/domain/series/controller/SeriesController.java
server/src/main/java/com/codestates/hobby/domain/series/dto/SeriesDto.java
server/src/main/java/com/codestates/hobby/domain/series/entity/Series.java
server/src/main/java/com/codestates/hobby/domain/series/mapper/SeriesMapper.java
server/src/main/java/com/codestates/hobby/domain/series/repository/SeriesRepository.java
server/src/main/java/com/codestates/hobby/domain/series/service/SeriesService.java

- Series [#74]
- Dto에 유효성 검증을 추가 하였습니다.
-  fileInfo와의 조인 테이블을 없애고 그에 따라 controller와 service를 수정하였습니다.
- getAllByCategory 응답에 시리즈에 속한 첫번째 postId를 추가하였습니다.

[BE/Series] 유효성 검증 구현 및 리펙토링

---

server/src/main/java/com/codestates/hobby/domain/category/mapper/CategoryMapper.java
server/src/main/java/com/codestates/hobby/domain/category/service/CategoryService.java
server/src/main/java/com/codestates/hobby/domain/fileInfo/controller/FileInfoController.java
server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
server/src/main/java/com/codestates/hobby/domain/post/service/PostCommentService.java
server/src/main/java/com/codestates/hobby/domain/post/service/PostService.java
server/src/main/java/com/codestates/hobby/domain/series/service/SeriesService.java
server/src/main/java/com/codestates/hobby/domain/showcase/mapper/ShowcaseCommentMapper.java
server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseCommentService.java
server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseService.java
server/src/main/java/com/codestates/hobby/global/advice/GlobalExceptionAdvice.java
server/src/main/java/com/codestates/hobby/global/exception/ExceptionCode.java
server/src/main/java/com/codestates/hobby/global/response/ErrorResponse.java
server/src/test/java/com/codestates/hobby/domain/fileInfo/service/FileInfoServiceTest.java

- 예외 핸들러 수정 및 추가 
- ExceptionCode 추가

[BE] Exception 수정

---

server/src/main/java/com/codestates/hobby/domain/auth/Session/SessionConst.java
server/src/main/java/com/codestates/hobby/domain/auth/Session/SessionManager.java
server/src/main/java/com/codestates/hobby/domain/auth/controller/LoginController.java
server/src/main/java/com/codestates/hobby/domain/auth/dto/LoginDto.java
server/src/main/java/com/codestates/hobby/domain/auth/service/LoginService.java
server/src/main/java/com/codestates/hobby/domain/auth/service/MemberDetailsService.java
server/src/main/java/com/codestates/hobby/domain/auth/utils/CustomAuthorityUtils.java
server/src/main/java/com/codestates/hobby/domain/member/controller/MemberController.java
server/src/main/java/com/codestates/hobby/domain/member/dto/MemberDto.java
server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
server/src/main/java/com/codestates/hobby/global/config/SecurityConfig.java
server/src/main/java/com/codestates/hobby/global/exception/ExceptionCode.java
server/src/main/resources/application.yml

- [#155 ]
- Member 리팩토링
- 로그인 기능 구현
- Member의 role 추가
- 로그인 중인 멤버를 @SessionAttribute Member loginMember로 가져오게 변경함

[BE/Member] 로그인 구현 및 Member 리팩토링

---

server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommendController.java
server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommentController.java
server/src/main/java/com/codestates/hobby/domain/post/controller/PostQueryController.java
server/src/main/java/com/codestates/hobby/domain/post/dto/PostCommentDto.java
server/src/main/java/com/codestates/hobby/domain/post/dto/PostDto.java
server/src/main/java/com/codestates/hobby/domain/post/entity/Post.java
server/src/main/java/com/codestates/hobby/domain/post/mapper/PostCommentMapper.java
server/src/main/java/com/codestates/hobby/domain/post/mapper/PostMapper.java
server/src/main/java/com/codestates/hobby/domain/post/service/PostCommentService.java

- Post 전체에 대한 리팩토링
- Sesson 로그인을 위한 Controller Param 수정
- series, seriesThumbmail, seriesPost등 mapping 에러 해결
- isWriter 제거 및 메서드 제거
- mapper Set메서드 추가 생성

[BE/Post] Post 리팩토링

---

server/src/main/java/com/codestates/hobby/domain/series/controller/SeriesController.java
server/src/main/java/com/codestates/hobby/domain/series/dto/SeriesDto.java
server/src/main/java/com/codestates/hobby/domain/series/entity/Series.java
server/src/main/java/com/codestates/hobby/domain/series/mapper/SeriesMapper.java
server/src/main/java/com/codestates/hobby/domain/series/repository/SeriesRepository.java
server/src/main/java/com/codestates/hobby/domain/series/service/SeriesService.java

- Series 리팩토링
- FileInfo에 seriesId가 매핑 되도록 수정
- Series update시 원하는 정보만 기입할 수 있도록 변경
- 로그인 멤버를 SessionAttribute으로 받도록 변경
- 시리즈 단건 조회, 시리즈 전체 조회 추가
- 유효성 검증 추가
- 시리즈 리스트 조회시 첫번째 포스트의 정보도 같이 넘겨주도록 주도록 변경
- BusinessLogicException 적용
- 브랜치가 꼬여서 임시로 만들었습니다. 머지되면 닫을게요.

[BE/Series] Series 리팩토링

---

client/src/components/molecules/UserInfo.js
client/src/components/molecules/list/PostCard.js
client/src/components/molecules/list/SeriesCard.js
client/src/components/molecules/series/SeriesInfo.js
client/src/components/molecules/series/SeriesPostList.js
client/src/components/molecules/series/SeriesTitle.js
client/src/components/organisms/PageHeader.js
client/src/components/organisms/SeriesHeader.js
client/src/components/organisms/listContainter/PostListContainer.js
client/src/components/organisms/listContainter/SeriesListContainer.js
client/src/components/pages/PostListPage.js
client/src/components/pages/SeriesListPage.js
client/src/components/pages/SeriesPage.js
client/src/constants/dummyData.js
client/src/hooks/useGetPost.js
client/src/hooks/useGetPostList.js
client/src/hooks/useGetSeries.js
client/src/hooks/useGetSeriesList.js
client/src/hooks/useGetSeriesPostList.js

- 커스텀 훅 추가 
- refactor 
- 파라미터 최적화
- 커스텀 훅 추가 
- refactor 
- 파라미터 최적화

[FE] Post, Series List 구현 , Post, Series Page 구현

---

server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommentController.java
server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseQueryController.java
server/src/main/java/com/codestates/hobby/domain/showcase/dto/ShowcaseCommentDto.java
server/src/main/java/com/codestates/hobby/domain/showcase/entity/Showcase.java
server/src/main/java/com/codestates/hobby/domain/showcase/mapper/ShowcaseCommentMapper.java
server/src/main/java/com/codestates/hobby/domain/showcase/mapper/ShowcaseMapper.java
server/src/main/java/com/codestates/hobby/domain/showcase/repository/ShowcaseCommentRepository.java
server/src/main/java/com/codestates/hobby/domain/showcase/repository/ShowcaseRepository.java
server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseService.java
server/src/main/java/com/codestates/hobby/global/config/support/InfiniteScrollArgumentResolver.java
server/src/main/java/com/codestates/hobby/global/dto/DefaultPageInfo.java
server/src/main/java/com/codestates/hobby/global/dto/InfinitePageInfo.java
server/src/main/java/com/codestates/hobby/global/dto/MultiResponseDto.java
server/src/main/java/com/codestates/hobby/global/dto/PageInfo.java
server/src/test/java/com/codestates/hobby/domain/stub/ShowcaseCommentStub.java

- Showcase 목록 조회시 마지막 댓글 반환하는 방식 변경
- Showcase Comment 응답 DTO에서 `isItWriter` 제거
- 무한 스크롤 최대값 지정

[Be/Showcase] 댓글 반환하는 방식 변경

---

server/src/main/java/com/codestates/hobby/domain/auth/Session/SessionConst.java
server/src/main/java/com/codestates/hobby/domain/auth/handler/CustomLoginFailureHandler.java
server/src/main/java/com/codestates/hobby/domain/auth/handler/CustomLoginSuccessHandler.java
server/src/main/java/com/codestates/hobby/domain/fileInfo/service/MockFileInfoService.java
server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
server/src/main/java/com/codestates/hobby/global/config/SecurityConfig.java

- `Member`
- `FileInfo`와 연관관계 재설정
- `MockFileInfoService`
- 호출할때마다 다른 파일이름을 생성하도록 변경
- `Session`
- 패키지명 소문자로 변경
- `LoginHandler`
- dto 경로 최신화

[BE/Debug] 앱 실행시 발생하는 오류 수정

---

server/src/main/java/com/codestates/hobby/domain/post/entity/Post.java
server/src/main/java/com/codestates/hobby/global/config/SecurityConfig.java
server/src/main/resources/application-prod.yml

- `application.yml` datasource url 수정
- `authorizeHttpRequests` 임시로 모두 허용하도록 변경

[BE/Deploy] 오류 수정

---

client/src/components/molecules/SearchInput.js
client/src/components/molecules/sidbar/SidebarMenu.js
client/src/components/molecules/sidbar/SidebarTagsContainer.js
client/src/components/organisms/Header.js
client/src/components/organisms/Loginbox.js
client/src/components/organisms/Sidebar.js
client/src/components/pages/404ErrorPage.js
client/src/store/sidebarStore.js

- sidebar의 현재 탭을 표시하는 전용 store 생성
- Header의 버튼 클릭, 로그인, 로그아웃 등으로 인한 페이지 변화에 따른 사이드바 store 값 변경
closes #187

[FE] Sidebar 수정

---

.github/workflows/client.yml

[FE] Client 배포 workflow 구현

---

client/src/components/atoms/Loading.js
client/src/components/pages/SeriesListPage.js
client/src/components/pages/UserEditPage.js
client/src/components/pages/UserPage.js

- Loading 컴포넌트 구현
- 일부 페이지 적용
- 각자 담당하시는 페이지에 적용 부탁드립니다~
closes #201

[FE] Loading 컴포넌트 구현

---

client/src/App.js
client/src/components/atoms/Buttons.js
client/src/components/atoms/TextArea.js
client/src/components/molecules/showcase/ShowcaseImageInput.js
client/src/components/organisms/Dropdown.js
client/src/components/pages/SeriesCreatePage.js
client/src/components/pages/ShowcaseCreatePage.js
client/src/store/showcaseCreateStore.js

- #126 
- SeriesCreatePage 구현
- Dropdown 버그수정
- ShowcaseCreate 언마운트시 initStore 실행하도록 추가
- ShowcaseCreateStore 를 SeriesCreatePage 에서 재사용 가능하도록 state 추가

[FE] Series Create 페이지 구현

---

client/src/App.js
client/src/components/organisms/postcreate/PostCreateHeader.js
client/src/components/pages/PostCreatePage.js
client/src/components/pages/PostEditPage.js
client/src/constants/dummyData.js

- Post 생성 페이지 API 연결
- Post 수정 페이지 생성 및 Route 연결
- Post 수정 페이지 API 연결 및 컴포넌트 연결
closes #210

[FE] Post Edit 페이지 구현

---

client/src/components/atoms/signup/SignupComponents.js
client/src/components/molecules/signup/EmailBox.js
client/src/components/molecules/signup/EmailValidationBox.js
client/src/components/molecules/signup/NicknameBox.js
client/src/components/molecules/signup/PasswordBox.js
client/src/components/molecules/signup/PasswordCheckBox.js
client/src/components/organisms/Loginbox.js
client/src/components/organisms/Signupbox.js
client/src/components/organisms/postcreate/PostCreateButtons.js
client/src/components/pages/UserEditPage.js
client/src/constants/Messages.js

- 이메일 인증 로직 구현
- 이메일, 이메일 인증, 닉네임, 비밀번호, 비밀번호 인증 컴포넌트 분리
- constants 파일 변수명 언더바 추가

[FE] 회원가입 기능 수정

---

server/src/main/java/com/codestates/hobby/domain/category/dto/CategoryDto.java
server/src/main/java/com/codestates/hobby/domain/category/entity/Category.java
server/src/main/java/com/codestates/hobby/domain/category/mapper/CategoryMapper.java
server/src/main/java/com/codestates/hobby/domain/post/mapper/PostMapper.java
server/src/main/java/com/codestates/hobby/domain/series/mapper/SeriesMapper.java
server/src/test/java/com/codestates/hobby/domain/category/repository/CategoryRepositoryTest.java
server/src/test/java/com/codestates/hobby/domain/showcase/ShowcaseCommentControllerTest.java
server/src/test/java/com/codestates/hobby/domain/stub/ShowcaseStub.java

- 응답시 영어 이름으로 반환하도록 수정함
- Category entity 캐싱필드 변경

[BE/Category] 카테고리 영어 이름 반환하도록 수정 

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/components/atoms/Category.js
client/src/components/molecules/comments/Comment.js
client/src/components/molecules/comments/CommentContentsContainer.js
client/src/components/molecules/comments/CommentHeader.js
client/src/components/molecules/comments/CommentInputContainer.js
client/src/components/organisms/Dropdown.js
client/src/components/organisms/comment/Comments.js
client/src/components/organisms/showcase/ShowcaseModal.js
client/src/components/organisms/showcase/Showcasebox.js
client/src/components/pages/SearchPage.js
client/src/components/pages/ShowcaseCreatePage.js
client/src/components/pages/ShowcasePage.js
client/src/hooks/useCommentAPI.js
client/src/hooks/useGetPost.js
client/src/hooks/useInputImage.js
client/src/hooks/useIntersect.js
client/src/store/showcaseCreateStore.js
client/src/store/showcaseModalStore.js
client/src/store/showcaseStore.js

- #220 
- useCommentAPI 훅 무한렌더링 버그수정
- 이미지 업로드시 UInt8Array 를 보내도록 변경
- Comment 관련 컴포넌트 basePath 프롭 추가
- Dropdown 컴포넌트 버그수정
- Windowing 적용
- 작동하지 않는 API 수정

[FE] Showcase/Comment 버그수정 및 기능추가

---

server/src/main/java/com/codestates/hobby/domain/auth/handler/CustomLoginSuccessHandler.java
server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
server/src/main/java/com/codestates/hobby/domain/series/controller/SeriesController.java

[Be/member] 가입 로직 변경

---

server/src/main/java/com/codestates/hobby/domain/post/repository/PostRepository.java

##기타
- 배포가 우선인 것 같아 돌아가게 수정만 했습니다.

[Be/post]Post 리팩토링

---

server/build.gradle
server/src/main/java/com/codestates/hobby/global/config/MvcConfig.java
server/src/main/java/com/codestates/hobby/global/config/SecurityConfig.java
server/src/main/java/com/codestates/hobby/global/exception/GlobalExceptionAdvice.java
server/src/main/java/com/codestates/hobby/global/log/AccessLogFilter.java
server/src/main/java/com/codestates/hobby/global/log/DebugLogFilter.java
server/src/main/java/com/codestates/hobby/global/log/LoggingFilter.java
server/src/main/java/com/codestates/hobby/global/log/LoggingInterceptor.java
server/src/main/java/com/codestates/hobby/global/log/RequestBodyLogger.java
server/src/main/resources/application-prod.yml
server/src/main/resources/logback-spring.xml

- `logback`설정 
- 로깅 필터 및 인터셉터 구현
- 배포 속성 파일에 logging level 제거
- ExceptionAdvice Log level을 warn으로 변경

[BE/Log] 로깅 기능 구현

---

server/src/main/java/com/codestates/hobby/domain/fileInfo/service/FileInfoService.java
server/src/main/java/com/codestates/hobby/domain/fileInfo/service/GCSFileInfoService.java
server/src/main/java/com/codestates/hobby/domain/showcase/repository/ShowcaseRepository.java
server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseService.java

[BE/Showcase] Offset 오류 수정

---

server/src/main/java/com/codestates/hobby/domain/showcase/repository/ShowcaseCommentRepository.java
server/src/main/java/com/codestates/hobby/domain/showcase/repository/ShowcaseRepository.java

- Showcase, Showcase Comment JPQL에서 member.image에 대한 fetch join 제거

[BE/Showcase] profile에 대한 fetch join 제거

---

client/src/components/molecules/posts/PostContentViewer.js
client/src/components/molecules/posts/PostIndexLIstRender.js

- Viewer 컨텐츠 로딩되도록 수정
closes #247

[FE] Post 페이지 뷰어 수정

---

client/src/components/molecules/comments/Comment.js
client/src/components/molecules/comments/CommentContentsContainer.js
client/src/components/molecules/comments/CommentInputContainer.js
client/src/components/organisms/comment/Comments.js
client/src/components/organisms/showcase/Showcasebox.js
client/src/components/pages/SeriesCreatePage.js
client/src/constants/Messages.js
client/src/hooks/useCommentAPI.js
client/src/store/contentCreateStore.js
client/src/store/showcaseStore.js

- SeriesCreate 페이지 버그수정
- SeriesCreate 페이지 유효성 검사 추가

[FE] SeriesCreate 버그수정

---

server/src/main/resources/logback-spring.xml

[BE/Log] timezone 변경

---

client/src/components/atoms/TextEditor.js
client/src/functions/getSignedUrl.js
client/src/functions/uploadImage.js

[FE] Post 페이지 이미지 업로드 로직 구현

---

client/src/components/molecules/ImageCard.js
client/src/components/organisms/showcase/ShowcaseModal.js
client/src/components/organisms/showcase/Showcasebox.js
client/src/constants/Categories.js

[FE] Category prop 수정

---

server/src/main/java/com/codestates/hobby/global/config/SecurityConfig.java

- `/auto/certifications` 요청시 익명 사용자 허용하도록 변경

[BE/Cert] authorizeHttpRequests 수정

---

server/src/main/java/com/codestates/hobby/domain/common/Writing.java
server/src/main/java/com/codestates/hobby/domain/member/repository/MemberRepository.java
server/src/main/java/com/codestates/hobby/domain/post/controller/PostQueryController.java
server/src/main/java/com/codestates/hobby/domain/post/entity/Post.java
server/src/main/java/com/codestates/hobby/domain/post/mapper/PostMapper.java
server/src/main/java/com/codestates/hobby/domain/post/repository/PostCommentRepository.java
server/src/main/java/com/codestates/hobby/domain/post/repository/PostRepository.java
server/src/main/java/com/codestates/hobby/domain/post/service/PostService.java
server/src/main/java/com/codestates/hobby/domain/post/service/PostValidationService.java
server/src/main/java/com/codestates/hobby/global/exception/ExceptionCode.java
server/src/main/resources/application-local.yml
server/src/main/resources/application-prod.yml

- Post 조회수 증가를 위한 수정
- Post 디폴트 썸네일 설정
- update에러 해결
- SimpleResponse의 content 제거
- 쿼리문 EntityGraph를 사용한 수정
- Doesn't Belong This  Member 코드 변경
- ThreadPool, ConnectionPool 설정
- 우선적으로 Post create에 대한 이중 호출만 문제 해결

[BE/Post] Post 리팩토링 및, Thread pool, Connecton pool 설정

---

client/src/components/molecules/Pagination.js
client/src/components/molecules/comments/CommentContentsContainer.js
client/src/components/organisms/comment/Comments.js
client/src/hooks/useCommentAPI.js

Co-authored-by: HJeong1200 <HJeong1200@users.noreply.github.com>

Co-authored-by: atiakr <atiakr@users.noreply.github.com>
